const state={files:{balance:null,resultados:null,flujo:null},data:{},rows:[]};
const fmt=n=>new Intl.NumberFormat('es-PY',{maximumFractionDigits:0}).format(Number(n)||0);
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
function setStatus(id,file){document.getElementById(id).textContent=file?file.name+' · '+Math.round(file.size/1024)+' KB':'Sin archivo'}
['balance','resultados','flujo'].forEach(k=>document.getElementById(k).addEventListener('change',e=>{state.files[k]=e.target.files[0]||null;setStatus({balance:'sb',resultados:'sr',flujo:'sf'}[k],state.files[k])}));
async function parseCsv(file){let s=await file.text();let lines=s.split(/\r?\n/).filter(x=>x.trim());let rows=lines.map(l=>{let a=[],cur='',q=false;for(let i=0;i<l.length;i++){let c=l[i];if(c==='"'){if(q&&l[i+1]==='"'){cur+='"';i++}else q=!q}else if((c===','||c===';')&&!q){a.push(cur);cur=''}else cur+=c}a.push(cur);return a});return {sheets:[{name:'CSV',rows}]}}
async function parseFile(file){let ext=file.name.toLowerCase().split('.').pop();if(ext==='csv')return parseCsv(file);if(ext==='xlsx'){if(!window.XLSX){throw new Error('Lector Excel no disponible en esta sesión. Se incorporará como dependencia local en la siguiente compilación.')}let buf=await file.arrayBuffer();let wb=XLSX.read(buf,{type:'array'});return {sheets:wb.SheetNames.map(n=>({name:n,rows:XLSX.utils.sheet_to_json(wb.Sheets[n],{header:1,defval:''})}))};}throw new Error('Formato no admitido: '+ext)}
function scoreSheet(sheet){let rows=sheet.rows||[];let text=rows.slice(0,40).map(r=>r.map(norm).join(' ')).join(' ');let score=0;if(/202[0-9]/.test(text))score+=3;if(/cuenta|concepto|descripcion|detalle/.test(text))score+=3;if(rows.length>5)score+=1;return score}
function detectSheet(parsed){return parsed.sheets.slice().sort((a,b)=>scoreSheet(b)-scoreSheet(a))[0]}
function previewSheet(name,parsed){let sh=detectSheet(parsed);let rows=sh?.rows||[];let periods=[];for(const r of rows.slice(0,12)){for(const c of r){let m=String(c).match(/20\d{2}/g);if(m)periods.push(...m)}}periods=[...new Set(periods)];return {name,selected:sh?.name||'',rows:rows.slice(0,12),periods}}
async function procesarArchivos(){let status=document.getElementById('loadStatus');status.textContent='Leyendo archivos...';let files=state.files;if(!files.balance&&!files.resultados&&!files.flujo){status.textContent='Cargá al menos un estado financiero.';return}let previews=[];try{for(const [key,file] of Object.entries(files)){if(!file)continue;let parsed=await parseFile(file);previews.push(previewSheet(key,parsed));state.data[key]=parsed}document.getElementById('periodos').value=[...new Set(previews.flatMap(x=>x.periods))].sort().join(', ');document.getElementById('previewBody').innerHTML=previews.map(p=>`<h3>${p.name.toUpperCase()}</h3><p><b>Hoja seleccionada:</b> ${p.selected||'No identificada'}<br><b>Períodos detectados:</b> ${p.periods.join(', ')||'No identificados'}</p><table class="table"><thead><tr>${(p.rows[0]||[]).map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${p.rows.slice(1,6).map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table>`).join('');document.getElementById('preview').classList.remove('hidden');status.textContent='Lectura completada. Revisá el control de lectura antes de ejecutar las pruebas.'}catch(e){status.textContent='Error de lectura: '+e.message}}
function cargarDemo(){document.getElementById('cliente').value='Henrique Blanco';document.getElementById('ruc').value='';document.getElementById('ejercicio').value='2025';document.getElementById('periodos').value='2024, 2025';document.getElementById('preview').classList.remove('hidden');document.getElementById('previewBody').innerHTML='<p><b>Caso demostrativo:</b> Henrique Blanco 2024–2025.</p><p>Esta acción solo sirve para validar la lógica del motor. La auditoría con datos reales se ejecutará cuando los archivos sean cargados.</p>';}
